
entrypoint: examples.terminal_bench.entrypoints.main_tbench

config_groups:
  terminal_bench_config: terminal_bench

terminal_bench:
  trials_dir: null

  harbor:
    name: terminus-2
    max_episodes: 999999
    enable_summarize: false
    store_all_messages: true
    enable_episode_logging: false

    override_timeout_sec: 900

    override_cpus: 1
    override_memory_mb: 2048
    override_storage_mb: 2048


    verifier_override_timeout_sec: 120

    max_retries: 3
    min_wait_sec: 60.0
    max_wait_sec: 600.0
    wait_multiplier: 2.0

    exclude_exceptions:
      - AgentTimeoutError
      - VerifierTimeoutError
      - RewardFileNotFoundError
      - RewardFileEmptyError
      - VerifierOutputParseError
      - ContextLengthExceededError

    n_concurrent_trials: 16

    log_level: WARNING

    enable_reward_shaping: false

  model_info:
    max_input_tokens: 30900
    max_output_tokens: 2048

trainer:
  strategy: fsdp2
  algorithm:
    advantage_estimator: grpo
    use_kl_loss: true
    kl_loss_coef: 0.001
    grpo_norm_by_std: true
    eps_clip_low: 0.2
    eps_clip_high: 0.2
    loss_reduction: token_mean

  epochs: 2
  update_epochs_per_batch: 1

  train_batch_size: 16
  policy_mini_batch_size: 8
  eval_batch_size: 32

  micro_forward_batch_size_per_gpu: 1
  micro_train_batch_size_per_gpu: 1

  max_prompt_length: 999999

  eval_interval: 999999
  eval_before_train: false
  ckpt_interval: 10
  resume_mode: latest

  project_name: OpenThoughts-Agent
  log_level: INFO

  run_name: null
  ckpt_path: null
  export_path: null

  policy:
    optimizer_config:
      lr: 5.0e-7
      weight_decay: 0.01
      adam_betas: [0.9, 0.999]
      max_grad_norm: 1.0

  ref:
    fsdp_config:
      cpu_offload: false
      reshard_after_forward: true

  placement:
    colocate_all: true
    policy_num_nodes: null
    ref_num_nodes: null
    policy_num_gpus_per_node: null
    ref_num_gpus_per_node: null

generator:
  backend: vllm
  timeout_multiplier: 2.0
  model_dtype: bfloat16
  enforce_eager: false

  inference_engine_tensor_parallel_size: 2
  num_inference_engines: null

  n_samples_per_prompt: 4
  eval_n_samples_per_prompt: 4

  gpu_memory_utilization: 0.90

  max_num_seqs: 64
  max_num_batched_tokens: 32768

  enable_prefix_caching: true
  enable_chunked_prefill: true

  run_engines_locally: true
  weight_sync_backend: nccl
  async_engine: true
  batched: true
  enable_http_endpoint: true
  enable_ray_prometheus_stats: false

  append_eos_token_after_stop_str_in_multi_turn: true
  max_turns: 999999

  sampling_params:
    max_generate_length: 8192
    temperature: 1.0
    top_p: 0.95
    top_k: -1

  engine_init_kwargs:
    max_model_len: 32768
    custom_chat_template_chat_completion_path: chat_templates/qwen3_thinking_acc.jinja2

data:
  train_data: []
  val_data: ["open-thoughts/OpenThoughts-TB-dev"]
