"""Calendar-scheduling verifier: parse agent JSON, check duration/time constraints."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Calendar-scheduling verifier — generated by nemotron_gym.

Expects agent to write a JSON list of events to /app/answer.txt. Each event:
  {"event_id": int, "event_name": str, "start_time": "HH:MM", "duration": int, ...}

The verifier checks:
  - JSON parses to a list
  - Required event_ids (from verifier_data.expected_events) all present
  - Per-event: duration matches expected, start_time within [min_time, max_time],
    end_time (start + duration) <= max_time, optional constraint phrase
    pseudo-checked.

`constraint` is left as a soft check — full natural-language parsing is out of
scope; we honor it only when it matches a small set of canonical patterns.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _parse_time(s: object) -> int | None:
    if not isinstance(s, str):
        return None
    m = re.match(r"^(\d{1,2}):(\d{2})$", s.strip())
    if not m:
        return None
    h, mi = int(m.group(1)), int(m.group(2))
    if not (0 <= h <= 23 and 0 <= mi <= 59):
        return None
    return h * 60 + mi


def _check_constraint(constraint: object, start_min: int, end_min: int) -> tuple[bool, str]:
    """Soft-check the natural-language `constraint` field.

    Recognized patterns (case-insensitive):
      - "before <H>(am|pm)"  → end <= time
      - "after <H>(am|pm)"   → start >= time
      - "at <H>(:MM)?(am|pm)" → start == time
      - "between <T1> and <T2>" → start >= T1 AND end <= T2
    Unrecognized constraints pass (soft).
    """
    if constraint in (None, "", []):
        return True, "no-constraint"
    if not isinstance(constraint, str):
        return True, "non-string-constraint (soft pass)"
    c = constraint.strip().lower()

    def _to_min(h: int, mi: int, ampm: str | None) -> int:
        h = h % 12
        if ampm == "pm":
            h += 12
        return h * 60 + mi

    m = re.match(r"^before\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$", c)
    if m:
        h, mi, ampm = int(m.group(1)), int(m.group(2) or 0), m.group(3)
        t = _to_min(h, mi, ampm)
        return end_min <= t, f"before {h}:{mi:02d}{ampm or ''} -> end_min={end_min} <= {t}"
    m = re.match(r"^after\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$", c)
    if m:
        h, mi, ampm = int(m.group(1)), int(m.group(2) or 0), m.group(3)
        t = _to_min(h, mi, ampm)
        return start_min >= t, f"after {h}:{mi:02d}{ampm or ''} -> start_min={start_min} >= {t}"
    m = re.match(r"^at\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$", c)
    if m:
        h, mi, ampm = int(m.group(1)), int(m.group(2) or 0), m.group(3)
        t = _to_min(h, mi, ampm)
        return start_min == t, f"at {h}:{mi:02d}{ampm or ''} -> start_min={start_min} == {t}"
    m = re.match(
        r"^between\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s+and\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$",
        c,
    )
    if m:
        h1, mi1, ap1, h2, mi2, ap2 = m.groups()
        t1 = _to_min(int(h1), int(mi1 or 0), ap1)
        t2 = _to_min(int(h2), int(mi2 or 0), ap2)
        return (start_min >= t1 and end_min <= t2), f"between [{t1},{t2}] -> [{start_min},{end_min}]"
    return True, f"unrecognized constraint (soft pass): {constraint!r}"


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_events", {})
    if not isinstance(expected, dict) or not expected:
        print("expected_events missing", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    # Try to parse as JSON. Tolerate code-fence wrapping.
    fence = re.search(r"```(?:json)?\s*(.*?)```", raw, flags=re.DOTALL)
    candidate = fence.group(1) if fence else raw
    try:
        events = json.loads(candidate)
    except Exception as e:
        print(f"JSON parse error: {e}")
        return 0
    if not isinstance(events, list):
        print(f"expected JSON list, got {type(events).__name__}")
        return 0
    by_id: dict[int, dict] = {}
    for ev in events:
        if not isinstance(ev, dict):
            continue
        ev_id = ev.get("event_id")
        if isinstance(ev_id, int):
            by_id[ev_id] = ev
    all_ok = True
    for eid_str, spec in expected.items():
        try:
            eid = int(eid_str)
        except (TypeError, ValueError):
            continue
        if not isinstance(spec, dict):
            continue
        if eid not in by_id:
            print(f"[event {eid}] MISSING")
            all_ok = False
            continue
        actual = by_id[eid]
        exp_duration = spec.get("duration")
        got_duration = actual.get("duration")
        if exp_duration != got_duration:
            print(f"[event {eid}] duration mismatch: got {got_duration} expected {exp_duration}")
            all_ok = False
            continue
        start = _parse_time(actual.get("start_time"))
        if start is None:
            print(f"[event {eid}] missing/invalid start_time {actual.get('start_time')!r}")
            all_ok = False
            continue
        min_t = _parse_time(spec.get("min_time"))
        max_t = _parse_time(spec.get("max_time"))
        if min_t is None or max_t is None:
            print(f"[event {eid}] expected min/max_time invalid")
            all_ok = False
            continue
        end = start + int(exp_duration)
        if start < min_t or end > max_t:
            print(f"[event {eid}] out of window: [{start},{end}] vs [{min_t},{max_t}]")
            all_ok = False
            continue
        ok, reason = _check_constraint(spec.get("constraint"), start, end)
        print(f"[event {eid}] {'PASS' if ok else 'FAIL'}: {reason}")
        if not ok:
            all_ok = False
    print(f"all_events_ok={all_ok}")
    return 1 if all_ok else 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
