"""Instruction-following verifier: dispatch on instruction_id_list constraints.

Implements a subset of Google's IFEval check semantics, declarative. This
keeps the container slim — we don't pull in google-research/ifeval, but the
constraint names match its taxonomy so we can swap to it later.
"""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""IFEval-style constraint verifier — generated by nemotron_gym.

Reads `instruction_id_list` and per-instruction `kwargs` from verifier_data.json
and runs each check against /app/answer.txt. Passes iff every constraint passes.

Implements common checks; unknown instruction IDs are reported as "unsupported"
and treated as a fail (so unsupported tasks don't silently rubber-stamp).
"""
from __future__ import annotations

import json
import pathlib
import re
import sys
from collections.abc import Callable
from typing import Any

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


_PARA_SEP = re.compile(r"\n\s*\n+")


def _paragraphs(text: str) -> list[str]:
    return [p for p in _PARA_SEP.split(text.strip()) if p.strip()]


def _sentences(text: str) -> list[str]:
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s.strip()]


def _words(text: str) -> list[str]:
    return re.findall(r"[A-Za-z0-9'\-]+", text)


def _count_letters(text: str, letter: str) -> int:
    return sum(1 for c in text.lower() if c == letter.lower())


# --- Constraint implementations ---------------------------------------------

CONSTRAINTS: dict[str, Callable[[str, dict], tuple[bool, str]]] = {}


def constraint(name: str):
    def wrap(fn):
        CONSTRAINTS[name] = fn
        return fn
    return wrap


@constraint("length_constraints:number_paragraphs")
def _number_paragraphs(text: str, kw: dict) -> tuple[bool, str]:
    n = kw.get("num_paragraphs")
    if not isinstance(n, int):
        return False, "missing num_paragraphs"
    actual = len(_paragraphs(text))
    return actual == n, f"paragraphs={actual} expected={n}"


@constraint("length_constraints:number_words")
def _number_words(text: str, kw: dict) -> tuple[bool, str]:
    rel = kw.get("relation", "at least")
    n = kw.get("num_words")
    if not isinstance(n, int):
        return False, "missing num_words"
    actual = len(_words(text))
    if rel == "at least":
        ok = actual >= n
    elif rel == "less than":
        ok = actual < n
    elif rel == "at most":
        ok = actual <= n
    else:
        return False, f"unsupported relation: {rel}"
    return ok, f"words={actual} rel={rel} n={n}"


@constraint("length_constraints:number_sentences")
def _number_sentences(text: str, kw: dict) -> tuple[bool, str]:
    rel = kw.get("relation", "at least")
    n = kw.get("num_sentences")
    if not isinstance(n, int):
        return False, "missing num_sentences"
    actual = len(_sentences(text))
    if rel == "at least":
        ok = actual >= n
    elif rel == "less than":
        ok = actual < n
    elif rel == "at most":
        ok = actual <= n
    else:
        return False, f"unsupported relation: {rel}"
    return ok, f"sentences={actual} rel={rel} n={n}"


@constraint("length_constraints:nth_paragraph_first_word")
def _nth_paragraph_first_word(text: str, kw: dict) -> tuple[bool, str]:
    n = kw.get("num_paragraphs")
    nth = kw.get("nth_paragraph")
    fw = kw.get("first_word")
    paras = _paragraphs(text)
    if not isinstance(n, int) or not isinstance(nth, int) or not isinstance(fw, str):
        return False, "missing kwargs"
    if len(paras) != n or nth < 1 or nth > len(paras):
        return False, f"paragraphs={len(paras)} need={n} nth={nth}"
    para = paras[nth - 1]
    actual_first = _words(para)
    if not actual_first or actual_first[0].lower() != fw.lower():
        return False, f"got first_word={actual_first[:1]} expected={fw!r}"
    return True, "ok"


@constraint("keywords:forbidden_words")
def _forbidden_words(text: str, kw: dict) -> tuple[bool, str]:
    forbidden = kw.get("forbidden_words", [])
    if not isinstance(forbidden, list):
        return False, "forbidden_words must be list"
    low = text.lower()
    hits = [w for w in forbidden if isinstance(w, str) and w.lower() in low]
    return not hits, f"hits={hits}"


@constraint("keywords:word_once")
def _word_once(text: str, kw: dict) -> tuple[bool, str]:
    keyword = kw.get("keyword")
    if not isinstance(keyword, str):
        return False, "missing keyword"
    count = len(re.findall(r"\b" + re.escape(keyword) + r"\b", text, flags=re.IGNORECASE))
    return count == 1, f"count={count} keyword={keyword!r}"


@constraint("keywords:letter_frequency")
def _letter_frequency(text: str, kw: dict) -> tuple[bool, str]:
    letter = kw.get("letter")
    rel = kw.get("let_relation", "at least")
    n = kw.get("let_frequency")
    if not (isinstance(letter, str) and len(letter) == 1 and isinstance(n, int)):
        return False, "bad kwargs"
    actual = _count_letters(text, letter)
    if rel == "at least":
        ok = actual >= n
    elif rel == "less than":
        ok = actual < n
    else:
        return False, f"unsupported relation: {rel}"
    return ok, f"letter={letter} count={actual} rel={rel} n={n}"


@constraint("change_case:english_capital")
def _english_capital(text: str, kw: dict) -> tuple[bool, str]:
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return False, "no letters"
    ok = all(c.isupper() for c in letters)
    return ok, f"all_upper={ok}"


@constraint("change_case:english_lowercase")
def _english_lowercase(text: str, kw: dict) -> tuple[bool, str]:
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return False, "no letters"
    ok = all(c.islower() for c in letters)
    return ok, f"all_lower={ok}"


@constraint("punctuation:no_comma")
def _no_comma(text: str, kw: dict) -> tuple[bool, str]:
    return "," not in text, f"has_comma={',' in text}"


@constraint("startend:end_checker")
def _end_checker(text: str, kw: dict) -> tuple[bool, str]:
    end_phrase = kw.get("end_phrase")
    if not isinstance(end_phrase, str):
        return False, "missing end_phrase"
    return text.rstrip().endswith(end_phrase), f"ends_with={end_phrase!r}"


@constraint("startend:quotation")
def _quotation(text: str, kw: dict) -> tuple[bool, str]:
    s = text.strip()
    ok = (s.startswith('"') and s.endswith('"')) or (s.startswith('"') and s.endswith('"'))
    return ok, f"quoted={ok}"


@constraint("detectable_format:number_bullet_lists")
def _bullet_lists(text: str, kw: dict) -> tuple[bool, str]:
    n = kw.get("num_bullets")
    if not isinstance(n, int):
        return False, "missing num_bullets"
    bullets = sum(1 for line in text.splitlines() if re.match(r"^\s*[\*\-]\s+", line))
    return bullets == n, f"bullets={bullets} expected={n}"


@constraint("detectable_format:title")
def _title(text: str, kw: dict) -> tuple[bool, str]:
    return bool(re.search(r"<<[^<>\n]+>>", text)), "title_marker"


@constraint("detectable_format:json_format")
def _json_format(text: str, kw: dict) -> tuple[bool, str]:
    try:
        json.loads(text.strip())
        return True, "json_parses"
    except Exception as e:
        return False, f"json_parse_error: {e}"


@constraint("detectable_format:multiple_sections")
def _multiple_sections(text: str, kw: dict) -> tuple[bool, str]:
    n = kw.get("num_sections")
    splitter = kw.get("section_spliter") or kw.get("section_splitter") or "Section"
    if not isinstance(n, int) or not isinstance(splitter, str):
        return False, "bad kwargs"
    pat = re.compile(re.escape(splitter) + r"\s*\d+", flags=re.IGNORECASE)
    actual = len(pat.findall(text))
    return actual == n, f"sections={actual} expected={n} splitter={splitter!r}"


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    instructions: list[str] = data.get("instruction_id_list", [])
    kwargs_list: list[dict | None] = data.get("kwargs", [])
    if not isinstance(instructions, list) or not isinstance(kwargs_list, list):
        print("malformed verifier_data", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    text = ANSWER.read_text(errors="replace")
    if not instructions:
        print("no constraints to check (vacuous pass)")
        return 1
    while len(kwargs_list) < len(instructions):
        kwargs_list.append({})
    all_ok = True
    for inst, kw in zip(instructions, kwargs_list):
        if not isinstance(inst, str):
            print(f"non-string instruction id: {inst!r}")
            all_ok = False
            continue
        if kw is None:
            kw = {}
        fn = CONSTRAINTS.get(inst)
        if fn is None:
            print(f"[{inst}] UNSUPPORTED — failing closed")
            all_ok = False
            continue
        try:
            ok, detail = fn(text, kw)
        except Exception as e:
            ok, detail = False, f"check exception: {e}"
        print(f"[{inst}] {'PASS' if ok else 'FAIL'}: {detail}")
        if not ok:
            all_ok = False
    print(f"all_constraints_pass={all_ok}")
    return 1 if all_ok else 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
