"""Math verifier: extract \\boxed{...} from agent answer, compare to gold via sympy."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""Math \boxed{} verifier — generated by nemotron_gym."""
from __future__ import annotations

import json
import pathlib
import re
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _extract_boxed(text: str) -> str | None:
    # Find the LAST \boxed{...} with balanced braces; LLMs often put extra
    # working before the final boxed answer.
    idx = text.rfind(r"\boxed{")
    if idx < 0:
        return None
    depth = 0
    start = idx + len(r"\boxed{")
    for i in range(start, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            if depth == 0:
                return text[start:i].strip()
            depth -= 1
    return None


def _normalize_numeric(s: str) -> str:
    s = s.strip()
    s = s.replace(",", "")
    s = re.sub(r"\\!\\s*", "", s)
    s = re.sub(r"\\,\\s*", "", s)
    return s


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    expected = data.get("expected_answer", "")
    if not isinstance(expected, str):
        print("expected_answer must be str", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing — agent did not write answer", file=sys.stderr)
        return 0
    raw = ANSWER.read_text(errors="replace")
    extracted = _extract_boxed(raw)
    if extracted is None:
        # Fall back to the whole content trimmed.
        extracted = raw.strip()
    print(f"expected={expected!r}")
    print(f"extracted={extracted!r}")
    a = _normalize_numeric(extracted)
    b = _normalize_numeric(expected)
    if a == b:
        print("verdict: string-match")
        return 1
    try:
        from sympy import Eq, simplify, sympify
        from sympy.parsing.latex import parse_latex
    except Exception as e:
        print(f"sympy unavailable ({e}); falling back to string compare only")
        return 0
    parsers = []
    parsers.append(("sympify", lambda s: sympify(s)))
    parsers.append(("latex", lambda s: parse_latex(s)))
    for label, fn in parsers:
        try:
            ea = fn(a)
            eb = fn(b)
            if Eq(ea, eb) is True or simplify(ea - eb) == 0:
                print(f"verdict: sympy-match ({label})")
                return 1
        except Exception as e:
            print(f"{label} parse error: {e}")
    print("verdict: mismatch")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
