"""ReasoningGym verifier: delegate to upstream reasoning_gym.score() if available."""

VERIFIER_PY = r'''#!/usr/bin/env python3
"""ReasoningGym verifier — generated by nemotron_gym.

Tries `reasoning_gym` library's per-task scorer first; falls back to a
normalized exact-match against `answer`.
"""
from __future__ import annotations

import json
import pathlib
import re
import string
import sys

REWARD = pathlib.Path("/logs/verifier/reward.txt")
ANSWER = pathlib.Path("/app/answer.txt")
DATA = pathlib.Path("/tests/verifier_data.json")


def _write_reward(score: int) -> None:
    REWARD.parent.mkdir(parents=True, exist_ok=True)
    REWARD.write_text("1" if score else "0")


def _normalize(s: str) -> str:
    s = s.strip().lower()
    s = "".join(ch for ch in s if ch not in string.punctuation)
    return re.sub(r"\s+", " ", s).strip()


def _try_reasoning_gym(question: str, answer: str, entry: dict) -> int | None:
    """Returns 1/0 on a verdict, or None if reasoning_gym lib isn't usable."""
    try:
        import reasoning_gym  # type: ignore
    except ImportError:
        return None
    source = entry.get("metadata", {}).get("source_dataset")
    if not source:
        return None
    try:
        scorer = reasoning_gym.get_scorer(source)  # API may vary by version
    except Exception as e:
        print(f"reasoning_gym.get_scorer({source!r}) failed: {e}")
        return None
    try:
        score = scorer(answer=answer, entry=entry)
    except Exception as e:
        print(f"scorer call failed: {e}")
        return None
    if isinstance(score, (int, float)):
        return 1 if score >= 0.5 else 0
    return None


def main() -> int:
    if not DATA.exists():
        print("verifier_data.json missing", file=sys.stderr)
        return 0
    data = json.loads(DATA.read_text())
    question = data.get("question", "")
    expected = data.get("answer", "")
    if not isinstance(expected, str):
        print("answer must be str", file=sys.stderr)
        return 0
    if not ANSWER.exists():
        print("/app/answer.txt missing", file=sys.stderr)
        return 0
    got = ANSWER.read_text(errors="replace").strip()
    print(f"got={got[:200]!r} expected={expected[:200]!r}")
    rg_verdict = _try_reasoning_gym(question=question, answer=got, entry=data)
    if rg_verdict is not None:
        print(f"reasoning_gym verdict={rg_verdict}")
        return rg_verdict
    # Fallback: normalized exact-match.
    if _normalize(got) == _normalize(expected):
        print("verdict: normalized-match")
        return 1
    if expected and expected in got:
        print("verdict: substring-match")
        return 1
    print("verdict: mismatch")
    return 0


if __name__ == "__main__":
    score = 0
    try:
        score = main()
    except Exception as e:
        print(f"verifier exception: {e}", file=sys.stderr)
        score = 0
    _write_reward(score)
'''
